### ISSUE TITLE
Level file format

### ISSUE THREAD

**Issue by rexim** [rexim/beatwave#12]
Split in #138 

### Pieces

- [x] #139 Define level file schema
- [x] #140 Refactor Game class
- [x] #141 Implement Level class
- [ ] #151 Investigate Sigmentation Fault on using PathCorrectors by value
- [ ] #153 Implement XML constructor for Tunnel
- [ ] #152 Implement XML constructor for Player
- [ ] #150 Implement XML constructor for path corrector swarm
- [ ] #142 Extract the event loop into a separate entity
